config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :perms
  resources :user_perms
  resources :proj_types
  resources :clients
  resources :providers
  resources :matches
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  root to: 'matches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_perm.rb
class UserPerm < ApplicationRecord
  belongs_to :user
end

app/controllers/user_perms_controller.rb
class UserPermsController < AdminController
  before_action :set_user_perm, only: [:show, :edit, :update, :destroy]

  # GET /user_perms
  # GET /user_perms.json
  def index
    @user_perms = UserPerm.all
  end

  # GET /user_perms/1
  # GET /user_perms/1.json
  def show
  end

  # GET /user_perms/new
  def new
    @user_perm = UserPerm.new
  end

  # GET /user_perms/1/edit
  def edit
  end

  # POST /user_perms
  # POST /user_perms.json
  def create
    @user_perm = UserPerm.new(user_perm_params)

    respond_to do |format|
      if @user_perm.save
        format.html { redirect_to @user_perm, notice: 'User perm was successfully created.' }
        format.json { render :show, status: :created, location: @user_perm }
      else
        format.html { render :new }
        format.json { render json: @user_perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_perms/1
  # PATCH/PUT /user_perms/1.json
  def update
    respond_to do |format|
      if @user_perm.update(user_perm_params)
        format.html { redirect_to @user_perm, notice: 'User perm was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_perm }
      else
        format.html { render :edit }
        format.json { render json: @user_perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_perms/1
  # DELETE /user_perms/1.json
  def destroy
    @user_perm.destroy
    respond_to do |format|
      format.html { redirect_to user_perms_url, notice: 'User perm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_perm
      @user_perm = UserPerm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_perm_params
      params.require(:user_perm).permit(:user_id, :perm_id)
    end
end

app/helpers/user_perms_helper.rb
module UserPermsHelper
end

app/views/user_perms/_form.html.erb
<%= form_with(model: user_perm, local: true) do |form| %>
  <% if user_perm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_perm.errors.count, "error") %> prohibited this user_perm from being saved:</h2>

      <ul>
      <% user_perm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :user_perm_user_id %>
  </div>

  <div class="field">
    <%= form.label :perm_id %>
    <%= form.number_field :perm_id, id: :user_perm_perm_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_perms/edit.html.erb
<h1>Editing User Perm</h1>

<%= render 'form', user_perm: @user_perm %>

<%= link_to 'Show', @user_perm %> |
<%= link_to 'Back', user_perms_path %>

app/views/user_perms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Perms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Perm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_perms.each do |user_perm| %>
      <tr>
        <td><%= user_perm.user_id %></td>
        <td><%= user_perm.perm_id %></td>
        <td><%= link_to 'Show', user_perm %></td>
        <td><%= link_to 'Edit', edit_user_perm_path(user_perm) %></td>
        <td><%= link_to 'Destroy', user_perm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Perm', new_user_perm_path %>

app/views/user_perms/new.html.erb
<h1>New User Perm</h1>

<%= render 'form', user_perm: @user_perm %>

<%= link_to 'Back', user_perms_path %>

app/views/user_perms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_perm.user_id %>
</p>

<p>
  <strong>Perm:</strong>
  <%= @user_perm.perm_id %>
</p>

<%= link_to 'Edit', edit_user_perm_path(@user_perm) %> |
<%= link_to 'Back', user_perms_path %>