config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :perms
  resources :user_perms
  resources :proj_types
  resources :clients
  resources :providers
  resources :matches
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  root to: 'matches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/perm.rb
class Perm < ApplicationRecord
end

app/controllers/perms_controller.rb
class PermsController < AdminController
  before_action :set_perm, only: [:show, :edit, :update, :destroy]

  # GET /perms
  # GET /perms.json
  def index
    @perms = Perm.all
  end

  # GET /perms/1
  # GET /perms/1.json
  def show
  end

  # GET /perms/new
  def new
    @perm = Perm.new
  end

  # GET /perms/1/edit
  def edit
  end

  # POST /perms
  # POST /perms.json
  def create
    @perm = Perm.new(perm_params)

    respond_to do |format|
      if @perm.save
        format.html { redirect_to @perm, notice: 'Perm was successfully created.' }
        format.json { render :show, status: :created, location: @perm }
      else
        format.html { render :new }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perms/1
  # PATCH/PUT /perms/1.json
  def update
    respond_to do |format|
      if @perm.update(perm_params)
        format.html { redirect_to @perm, notice: 'Perm was successfully updated.' }
        format.json { render :show, status: :ok, location: @perm }
      else
        format.html { render :edit }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perms/1
  # DELETE /perms/1.json
  def destroy
    @perm.destroy
    respond_to do |format|
      format.html { redirect_to perms_url, notice: 'Perm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perm
      @perm = Perm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perm_params
      params.require(:perm).permit(:description)
    end
end

app/helpers/perms_helper.rb
module PermsHelper
end

app/views/perms/_form.html.erb
<%= form_with(model: perm, local: true) do |form| %>
  <% if perm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perm.errors.count, "error") %> prohibited this perm from being saved:</h2>

      <ul>
      <% perm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :perm_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perms/edit.html.erb
<h1>Editing Perm</h1>

<%= render 'form', perm: @perm %>

<%= link_to 'Show', @perm %> |
<%= link_to 'Back', perms_path %>

app/views/perms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perms</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perms.each do |perm| %>
      <tr>
        <td><%= perm.description %></td>
        <td><%= link_to 'Show', perm %></td>
        <td><%= link_to 'Edit', edit_perm_path(perm) %></td>
        <td><%= link_to 'Destroy', perm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perm', new_perm_path %>

app/views/perms/new.html.erb
<h1>New Perm</h1>

<%= render 'form', perm: @perm %>

<%= link_to 'Back', perms_path %>

app/views/perms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @perm.description %>
</p>

<%= link_to 'Edit', edit_perm_path(@perm) %> |
<%= link_to 'Back', perms_path %>