config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :perms
  resources :user_perms
  resources :proj_types
  resources :clients
  resources :providers
  resources :matches
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  root to: 'matches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :client, :foreign_key => :sp_client_id, :primary_key => :sp_client_id, optional: true
  belongs_to :provider, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id , optional: true
  def self.exec_match(match_instance)
    match_provider = match_instance.sp_provider_id
    clients = Eligibility.where('sp_provider_id = ?',match_provider).pluck(:sp_client_id)
    client_ids = Client.where('sp_client_id IN (?) and in_process IS NULL',clients).order(:vi_score).reverse_order.pluck(:sp_client_id)
    client_id = client_ids[0]
    if client_id
      client = Client.where('sp_client_id = ?',client_id).first
      client.in_process = true
      client.save
      match_instance.sp_client_id = client_id
      match_instance.save
    else
      print('ended homelessness!!!')
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:sp_provider_id, :sp_client_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sp_provider_id %>
    <%= collection_select(:match, :sp_provider_id, Provider.all, :sp_provider_id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.provider.name%></td>
        <td><%= match.sp_client_id %></td>
        <%if current_user && current_user.admin?%>
          <td><%= link_to 'Show', match %></td>
          <td><%= link_to 'Edit', edit_match_path(match) %></td>
          <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @match.provider.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @match.sp_client_id %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>