config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :perms
  resources :user_perms
  resources :proj_types
  resources :clients
  resources :providers
  resources :matches
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations'}
  root to: 'matches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require 'csv'
  self.abstract_class = true
  def self.import_file(file)
    CSV.foreach(file.path, headers: true) do |row|
      self.create!(row.to_hash)
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  
  has_many :matches, :foreign_key => :sp_client_id, :primary_key => :sp_client_id 
  has_many :eligibilities, :foreign_key => :sp_client_id, :primary_key => :sp_client_id
  
#  def self.import(file, myclass)
#    CSV.foreach(file.path, headers: true) do |row|
#      myclass.create!(row.to_hash)
#    end
#  end
  
end

app/models/eligibility.rb
class Eligibility < ApplicationRecord
  belongs_to :client, :foreign_key => :sp_client_id, :primary_key => :sp_client_id 
  belongs_to :provider, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id 
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :client, :foreign_key => :sp_client_id, :primary_key => :sp_client_id, optional: true
  belongs_to :provider, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id , optional: true
  def self.exec_match(match_instance)
    match_provider = match_instance.sp_provider_id
    clients = Eligibility.where('sp_provider_id = ?',match_provider).pluck(:sp_client_id)
    client_ids = Client.where('sp_client_id IN (?) and in_process IS NULL',clients).order(:vi_score).reverse_order.pluck(:sp_client_id)
    client_id = client_ids[0]
    if client_id
      client = Client.where('sp_client_id = ?',client_id).first
      client.in_process = true
      client.save
      match_instance.sp_client_id = client_id
      match_instance.save
    else
      print('ended homelessness!!!')
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :providers, :foreign_key => :sp_organization_id, :primary_key => :sp_organization_id
  has_many :users, :foreign_key => :sp_organization_id, :primary_key => :sp_organization_id
end

app/models/perm.rb
class Perm < ApplicationRecord
end

app/models/proj_type.rb
class ProjType < ApplicationRecord
  has_many :providers
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :matches, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id
  has_many :eligibilities, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id
  belongs_to :organization, :foreign_key => :sp_organization_id, :primary_key => :sp_organization_id
  belongs_to :proj_type
  has_one :provider_perm, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id
end

app/models/provider_perm.rb
class ProviderPerm < ApplicationRecord
  belongs_to :provider, :foreign_key => :sp_provider_id, :primary_key => :sp_provider_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :organization, :foreign_key => :sp_organization_id, :primary_key => :sp_organization_id
  has_many :user_perms
end

app/models/user_perm.rb
class UserPerm < ApplicationRecord
  belongs_to :user
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action do 
    redirect_to root_path, alert: 'Access Denied' unless current_user && current_user.admin?
  end
end

app/controllers/perms_controller.rb
class PermsController < AdminController
  before_action :set_perm, only: [:show, :edit, :update, :destroy]

  # GET /perms
  # GET /perms.json
  def index
    @perms = Perm.all
  end

  # GET /perms/1
  # GET /perms/1.json
  def show
  end

  # GET /perms/new
  def new
    @perm = Perm.new
  end

  # GET /perms/1/edit
  def edit
  end

  # POST /perms
  # POST /perms.json
  def create
    @perm = Perm.new(perm_params)

    respond_to do |format|
      if @perm.save
        format.html { redirect_to @perm, notice: 'Perm was successfully created.' }
        format.json { render :show, status: :created, location: @perm }
      else
        format.html { render :new }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perms/1
  # PATCH/PUT /perms/1.json
  def update
    respond_to do |format|
      if @perm.update(perm_params)
        format.html { redirect_to @perm, notice: 'Perm was successfully updated.' }
        format.json { render :show, status: :ok, location: @perm }
      else
        format.html { render :edit }
        format.json { render json: @perm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perms/1
  # DELETE /perms/1.json
  def destroy
    @perm.destroy
    respond_to do |format|
      format.html { redirect_to perms_url, notice: 'Perm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perm
      @perm = Perm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perm_params
      params.require(:perm).permit(:description)
    end
end

app/controllers/proj_types_controller.rb
class ProjTypesController < AdminController
  before_action :set_proj_type, only: [:show, :edit, :update, :destroy]

  # GET /proj_types
  # GET /proj_types.json
  def index
    @proj_types = ProjType.all
  end

  # GET /proj_types/1
  # GET /proj_types/1.json
  def show
  end

  # GET /proj_types/new
  def new
    @proj_type = ProjType.new
  end

  # GET /proj_types/1/edit
  def edit
  end

  # POST /proj_types
  # POST /proj_types.json
  def create
    @proj_type = ProjType.new(proj_type_params)

    respond_to do |format|
      if @proj_type.save
        format.html { redirect_to @proj_type, notice: 'Proj type was successfully created.' }
        format.json { render :show, status: :created, location: @proj_type }
      else
        format.html { render :new }
        format.json { render json: @proj_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proj_types/1
  # PATCH/PUT /proj_types/1.json
  def update
    respond_to do |format|
      if @proj_type.update(proj_type_params)
        format.html { redirect_to @proj_type, notice: 'Proj type was successfully updated.' }
        format.json { render :show, status: :ok, location: @proj_type }
      else
        format.html { render :edit }
        format.json { render json: @proj_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proj_types/1
  # DELETE /proj_types/1.json
  def destroy
    @proj_type.destroy
    respond_to do |format|
      format.html { redirect_to proj_types_url, notice: 'Proj type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proj_type
      @proj_type = ProjType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proj_type_params
      params.require(:proj_type).permit(:proj_type_id, :description, :service_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/perms_helper.rb
module PermsHelper
end

app/helpers/proj_types_helper.rb
module ProjTypesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/user_perms_helper.rb
module UserPermsHelper
end

app/views/proj_types/_form.html.erb
<%= form_with(model: proj_type, local: true) do |form| %>
  <% if proj_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proj_type.errors.count, "error") %> prohibited this proj_type from being saved:</h2>

      <ul>
      <% proj_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :proj_type_description %>
  </div>

  <div class="field">
    <%= form.label :service_code %>
    <%= form.number_field :service_code, id: :proj_type_service_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proj_types/edit.html.erb
<h1>Editing Proj Type</h1>

<%= render 'form', proj_type: @proj_type %>

<%= link_to 'Show', @proj_type %> |
<%= link_to 'Back', proj_types_path %>

app/views/proj_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proj Types</h1>

<table>
  <thead>
    <tr>
      <th>Proj type</th>
      <th>Description</th>
      <th>Service code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proj_types.each do |proj_type| %>
      <tr>
        <td><%= proj_type.id %></td>
        <td><%= proj_type.description %></td>
        <td><%= proj_type.service_code %></td>
        <td><%= link_to 'Show', proj_type %></td>
        <td><%= link_to 'Edit', edit_proj_type_path(proj_type) %></td>
        <td><%= link_to 'Destroy', proj_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proj Type', new_proj_type_path %>

app/views/proj_types/new.html.erb
<h1>New Proj Type</h1>

<%= render 'form', proj_type: @proj_type %>

<%= link_to 'Back', proj_types_path %>

app/views/proj_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proj type:</strong>
  <%= @proj_type.proj_type_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @proj_type.description %>
</p>

<p>
  <strong>Service code:</strong>
  <%= @proj_type.service_code %>
</p>

<%= link_to 'Edit', edit_proj_type_path(@proj_type) %> |
<%= link_to 'Back', proj_types_path %>